config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { sessions: "users/sessions" }
  
  get 'static_pages/home'

  get 'static_pages/about'

  root to: "static_pages#home" #controller#action

  get '/static_pages' => 'static_pages#home', as: 'static_pages'
  
  get '/welcome' => 'static_pages#welcome', as: 'welcome'

  resources :users

  resources :tasks

  resources :taskets

end

app/models/tasket.rb
class Tasket < ActiveRecord::Base

	belongs_to :user
	has_many :tasks

	
	
end

app/controllers/taskets_controller.rb
class TasketsController < ApplicationController
  before_action :set_tasket, only: [:show, :edit, :update, :destroy]

  def daily_update
    User.all.each do |user|
      TasketMailer.daily_email(user).deliver_now!
    end
  end

  def welcome_update
    User.all.each do |user|
    TasketMailer.welcome_email(user).deliver
    end
  end

  # GET /taskets
  # GET /taskets.json
  def index
    @taskets = Tasket.all
    @user = current_user

  end

  # GET /taskets/1
  # GET /taskets/1.json
  def show
  end

  # GET /taskets/new
  def new
    @tasket = Tasket.new
  end

  # GET /taskets/1/edit
  def edit
  end

  # POST /taskets
  # POST /taskets.json
  def create
    @tasket = Tasket.new(tasket_params)
    @user = current_user
    respond_to do |format|
      if @tasket.save

        # Sends email to user when user is created.
      TasketMailer.welcome_email(@user).deliver


        format.html { redirect_to @tasket, notice: 'Tasket was successfully created.' }
        format.json { render :show, status: :created, location: @tasket }
      else
        format.html { render :new }
        format.json { render json: @tasket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /taskets/1
  # PATCH/PUT /taskets/1.json
  def update
    respond_to do |format|
      if @tasket.update(tasket_params)
        format.html { redirect_to @tasket, notice: 'Tasket was successfully updated.' }
        format.json { render :show, status: :ok, location: @tasket }
      else
        format.html { render :edit }
        format.json { render json: @tasket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taskets/1
  # DELETE /taskets/1.json
  def destroy
    @tasket.destroy
    respond_to do |format|
      format.html { redirect_to taskets_url, notice: 'Tasket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tasket
      @tasket = Tasket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tasket_params
      params.require(:tasket).permit(:name, :user_id)
    end
end

app/helpers/taskets_helper.rb
module TasketsHelper
end

app/views/taskets/_form.html.erb
<%= form_for(@tasket) do |f| %>
  <% if @tasket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tasket.errors.count, "error") %> prohibited this tasket from being saved:</h2>

      <ul>
      <% @tasket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/taskets/edit.html.erb
<h1>Editing Tasket</h1>

<%= render 'form' %>

<%= link_to 'Show', @tasket %> |
<%= link_to 'Back', taskets_path %>

app/views/taskets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Active Taskets for <%= @user.email %></h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
    <% @taskets.each do |tasket| %>


      <tr>
        <td><%= tasket.name %></td>
        <td><%= link_to 'Show', tasket %></td>
        <td><%= link_to 'Edit', edit_tasket_path(tasket) %></td>
        <td><%= link_to 'Destroy', tasket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
 
</table>

<br>

<%= link_to 'New Tasket', new_tasket_path %>

app/views/taskets/new.html.erb
<h1>New Tasket</h1>

<%= render 'form' %>

<%= link_to 'Back', taskets_path %>

app/views/taskets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tasket.name %>
  <br>
  User id: <%= @tasket.user_id %>
</p>

<%= link_to 'Edit', edit_tasket_path(@tasket) %> |
<%= link_to 'Back', taskets_path %>